# Reusable Workflow to deploy a new revision to Cloud Run

name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
        default: 'production'
      version:
        description: 'The version of the image to deploy'
        required: true
        type: string
        default: 'latest'
      service:
        description: 'The name of the Cloud Run service to deploy to'
        required: true
        type: string
        default: 'dpgraham-frontend'

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REPOSITORY: ${{ vars.REPOSITORY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  GOOGLE_REGISTRY_LOCATION: ${{ vars.GOOGLE_REGISTRY_LOCATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'


      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        id: auth
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          token_format: 'access_token'

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ inputs.service }}
          image: ${{ env.GOOGLE_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
          region: ${{ env.GOOGLE_REGISTRY_LOCATION }}
