# This Workflow deploys a Docker image to Google Cloud Run

name: On Release

on:
  release:
    types: [ published ]

jobs:
  build_gcp_image:
    name: Build Image for GCP
    uses: ./.github/workflows/build-gcp-image.yaml
    with:
      environment: production
    secrets: inherit

  deploy_to_cloud_run:
    name: Deploy to Cloud Run
    uses: ./.github/workflows/cloud-run-deploy.yaml
    needs: build_gcp_image
    with:
      environment: production
      version: ${{ needs.build_gcp_image.outputs.version }}
      service: dpgraham-frontend
    secrets: inherit

  build_ghcr_image:
    name: Build Image for GHCR
    uses: ./.github/workflows/build-ghcr-image.yaml
    secrets: inherit